// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ApplicationAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entitites.Models.Answer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.HasKey("AnswerId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("Entitites.Models.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExerciseId");

                    b.HasIndex("TestId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Entitites.Models.Lecture", b =>
                {
                    b.Property<Guid>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LectureId");

                    b.Property<string>("LectureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LectureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LectureId");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be"),
                            LectureName = "Arrays"
                        },
                        new
                        {
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f"),
                            LectureName = "Functions"
                        });
                });

            modelBuilder.Entity("Entitites.Models.LectureProgrammingLanguage", b =>
                {
                    b.Property<Guid>("LectureProgrammingLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LectureProgrammingLanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LectureId");

                    b.ToTable("LectureProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("03393a25-ec23-4bdb-b184-3e5d0bc2fe35"),
                            LanguageId = new Guid("8665c6cb-7dc0-4058-9bc7-7c65c7869d47"),
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("19c68284-a3fa-402d-a1f4-5649b8c18b08"),
                            LanguageId = new Guid("48e36ba7-6216-4b19-a671-066c0f5a8e0a"),
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("90b4f57a-18f5-488a-b845-bd00aaa996d0"),
                            LanguageId = new Guid("3a9723c8-af2c-46b9-a4cd-bcb32f5a90b6"),
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("af420390-3b21-4027-94a4-671fbd55af83"),
                            LanguageId = new Guid("bcd4aaec-f236-451a-92eb-7642471c8ecc"),
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("a1a3437c-e0e8-464e-952e-3b4cc39c665b"),
                            LanguageId = new Guid("8665c6cb-7dc0-4058-9bc7-7c65c7869d47"),
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("e0e6a27c-e642-4aff-9dd4-549d073ac5a6"),
                            LanguageId = new Guid("48e36ba7-6216-4b19-a671-066c0f5a8e0a"),
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("50118750-3894-4cb0-86c0-f6b3610a2be1"),
                            LanguageId = new Guid("3a9723c8-af2c-46b9-a4cd-bcb32f5a90b6"),
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("20cf18f8-c473-4004-86ed-25fe37c01d1b"),
                            LanguageId = new Guid("bcd4aaec-f236-451a-92eb-7642471c8ecc"),
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f")
                        });
                });

            modelBuilder.Entity("Entitites.Models.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LanguageId");

                    b.Property<string>("LanguageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LanguageType")
                        .HasColumnType("int");

                    b.HasKey("LanguageId");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("8665c6cb-7dc0-4058-9bc7-7c65c7869d47"),
                            LanguageDescription = "Opis: C je opštepriznati proceduralni programski jezik koji je nastao u Bell Labs-u 1972. godine. Poznat je po svojoj efikasnosti, fleksibilnosti i mogućnosti direktnog pristupa hardveru.\r\nKarakteristike: Statički tipiziran, niskog nivoa apstrakcije, podržava pokazivače, omogućava direktno upravljanje memorijom.\r\nPrimeri upotrebe: Razvoj operativnih sistema, sistemske aplikacije, ugrađeni sistemi.",
                            LanguageName = "C",
                            LanguageType = 1
                        },
                        new
                        {
                            LanguageId = new Guid("48e36ba7-6216-4b19-a671-066c0f5a8e0a"),
                            LanguageDescription = "Opis: C++ je proširenje jezika C koje uvodi koncepte objektno-orijentisanog programiranja (OOP). Razvijen je kao unapređenje jezika C, omogućavajući programerima da koriste OOP paradigmu.\r\nKarakteristike: Objektno-orijentisan, podržava nasleđivanje, polimorfizam, apstrakciju i inkapsulaciju, bogata standardna biblioteka.\r\nPrimeri upotrebe: Razvoj softvera, igara, operativnih sistema, aplikacija za računarsko modelovanje.",
                            LanguageName = "C++",
                            LanguageType = 0
                        },
                        new
                        {
                            LanguageId = new Guid("3a9723c8-af2c-46b9-a4cd-bcb32f5a90b6"),
                            LanguageDescription = "Opis: C# je moderan, objektno-orijentisan jezik razvijen od strane Microsoft-a. Namenjen je razvoju aplikacija na platformi .NET.\r\nKarakteristike: Objektno-orijentisan, podržava garbage collection, delegati, događaji, LINQ (Language Integrated Query), Lambda izraze.\r\nPrimeri upotrebe: Razvoj Windows aplikacija, web aplikacija, igara, mobilnih aplikacija.",
                            LanguageName = "C#",
                            LanguageType = 0
                        },
                        new
                        {
                            LanguageId = new Guid("bcd4aaec-f236-451a-92eb-7642471c8ecc"),
                            LanguageDescription = "Opis: Java je objektno-orijentisan, platformski nezavisan jezik razvijen od strane Sun Microsystems-a (sada deo Oracle-a). Poznat je po svojoj sigurnosti i portabilnosti.\r\nKarakteristike: Objektno-orijentisan, platformski nezavisan (rad na različitim operativnim sistemima), podržava garbage collection, izuzetno popularan u razvoju web i mobilnih aplikacija.\r\nPrimeri upotrebe: Razvoj web aplikacija, mobilnih aplikacija (Android), serverskih aplikacija, finansijskih sistema.",
                            LanguageName = "Java",
                            LanguageType = 0
                        });
                });

            modelBuilder.Entity("Entitites.Models.Test", b =>
                {
                    b.Property<Guid>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LectureProgrammingLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestId");

                    b.HasIndex("LectureProgrammingLanguageId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Entitites.Models.Answer", b =>
                {
                    b.HasOne("Entitites.Models.Exercise", "Exercise")
                        .WithMany("Answers")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Entitites.Models.Exercise", b =>
                {
                    b.HasOne("Entitites.Models.Test", "Test")
                        .WithMany("Exercises")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Entitites.Models.LectureProgrammingLanguage", b =>
                {
                    b.HasOne("Entitites.Models.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany("Lectures")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entitites.Models.Lecture", "Lecture")
                        .WithMany("ProgrammingLanguages")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("Entitites.Models.Test", b =>
                {
                    b.HasOne("Entitites.Models.LectureProgrammingLanguage", "LectureProgrammingLanguage")
                        .WithMany("Tests")
                        .HasForeignKey("LectureProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LectureProgrammingLanguage");
                });

            modelBuilder.Entity("Entitites.Models.Exercise", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Entitites.Models.Lecture", b =>
                {
                    b.Navigation("ProgrammingLanguages");
                });

            modelBuilder.Entity("Entitites.Models.LectureProgrammingLanguage", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Entitites.Models.ProgrammingLanguage", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("Entitites.Models.Test", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
