// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ApplicationAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entitites.Models.Lecture", b =>
                {
                    b.Property<Guid>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LectureId");

                    b.Property<string>("LectureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LectureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LectureId");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be"),
                            LectureName = "Arrays"
                        },
                        new
                        {
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f"),
                            LectureName = "Functions"
                        });
                });

            modelBuilder.Entity("Entitites.Models.LectureProgrammingLanguage", b =>
                {
                    b.Property<Guid>("LectureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LectureId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LectureProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be"),
                            LanguageId = new Guid("8665c6cb-7dc0-4058-9bc7-7c65c7869d47")
                        },
                        new
                        {
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be"),
                            LanguageId = new Guid("48e36ba7-6216-4b19-a671-066c0f5a8e0a")
                        },
                        new
                        {
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be"),
                            LanguageId = new Guid("3a9723c8-af2c-46b9-a4cd-bcb32f5a90b6")
                        },
                        new
                        {
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be"),
                            LanguageId = new Guid("bcd4aaec-f236-451a-92eb-7642471c8ecc")
                        },
                        new
                        {
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f"),
                            LanguageId = new Guid("8665c6cb-7dc0-4058-9bc7-7c65c7869d47")
                        },
                        new
                        {
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f"),
                            LanguageId = new Guid("48e36ba7-6216-4b19-a671-066c0f5a8e0a")
                        },
                        new
                        {
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f"),
                            LanguageId = new Guid("3a9723c8-af2c-46b9-a4cd-bcb32f5a90b6")
                        },
                        new
                        {
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f"),
                            LanguageId = new Guid("bcd4aaec-f236-451a-92eb-7642471c8ecc")
                        });
                });

            modelBuilder.Entity("Entitites.Models.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LanguageId");

                    b.Property<string>("LanguageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LanguageType")
                        .HasColumnType("int");

                    b.HasKey("LanguageId");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("8665c6cb-7dc0-4058-9bc7-7c65c7869d47"),
                            LanguageDescription = "Opis: C je opštepriznati proceduralni programski jezik koji je nastao u Bell Labs-u 1972. godine. Poznat je po svojoj efikasnosti, fleksibilnosti i mogućnosti direktnog pristupa hardveru.\r\nKarakteristike: Statički tipiziran, niskog nivoa apstrakcije, podržava pokazivače, omogućava direktno upravljanje memorijom.\r\nPrimeri upotrebe: Razvoj operativnih sistema, sistemske aplikacije, ugrađeni sistemi.",
                            LanguageName = "C",
                            LanguageType = 1
                        },
                        new
                        {
                            LanguageId = new Guid("48e36ba7-6216-4b19-a671-066c0f5a8e0a"),
                            LanguageDescription = "Opis: C++ je proširenje jezika C koje uvodi koncepte objektno-orijentisanog programiranja (OOP). Razvijen je kao unapređenje jezika C, omogućavajući programerima da koriste OOP paradigmu.\r\nKarakteristike: Objektno-orijentisan, podržava nasleđivanje, polimorfizam, apstrakciju i inkapsulaciju, bogata standardna biblioteka.\r\nPrimeri upotrebe: Razvoj softvera, igara, operativnih sistema, aplikacija za računarsko modelovanje.",
                            LanguageName = "C++",
                            LanguageType = 0
                        },
                        new
                        {
                            LanguageId = new Guid("3a9723c8-af2c-46b9-a4cd-bcb32f5a90b6"),
                            LanguageDescription = "Opis: C# je moderan, objektno-orijentisan jezik razvijen od strane Microsoft-a. Namenjen je razvoju aplikacija na platformi .NET.\r\nKarakteristike: Objektno-orijentisan, podržava garbage collection, delegati, događaji, LINQ (Language Integrated Query), Lambda izraze.\r\nPrimeri upotrebe: Razvoj Windows aplikacija, web aplikacija, igara, mobilnih aplikacija.",
                            LanguageName = "C#",
                            LanguageType = 0
                        },
                        new
                        {
                            LanguageId = new Guid("bcd4aaec-f236-451a-92eb-7642471c8ecc"),
                            LanguageDescription = "Opis: Java je objektno-orijentisan, platformski nezavisan jezik razvijen od strane Sun Microsystems-a (sada deo Oracle-a). Poznat je po svojoj sigurnosti i portabilnosti.\r\nKarakteristike: Objektno-orijentisan, platformski nezavisan (rad na različitim operativnim sistemima), podržava garbage collection, izuzetno popularan u razvoju web i mobilnih aplikacija.\r\nPrimeri upotrebe: Razvoj web aplikacija, mobilnih aplikacija (Android), serverskih aplikacija, finansijskih sistema.",
                            LanguageName = "Java",
                            LanguageType = 0
                        });
                });

            modelBuilder.Entity("Entitites.Models.LectureProgrammingLanguage", b =>
                {
                    b.HasOne("Entitites.Models.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany("Lectures")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entitites.Models.Lecture", "Lecture")
                        .WithMany("ProgrammingLanguages")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("Entitites.Models.Lecture", b =>
                {
                    b.Navigation("ProgrammingLanguages");
                });

            modelBuilder.Entity("Entitites.Models.ProgrammingLanguage", b =>
                {
                    b.Navigation("Lectures");
                });
#pragma warning restore 612, 618
        }
    }
}
