// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ApplicationAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entitites.Models.Answer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.HasKey("AnswerId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("Entitites.Models.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExerciseId");

                    b.HasIndex("TestId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Entitites.Models.Lecture", b =>
                {
                    b.Property<Guid>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LectureId");

                    b.Property<string>("LectureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LectureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LectureId");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be"),
                            LectureDescription = "Some Description.",
                            LectureName = "Arrays"
                        },
                        new
                        {
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f"),
                            LectureDescription = "Some Description.",
                            LectureName = "Functions"
                        });
                });

            modelBuilder.Entity("Entitites.Models.LectureProgrammingLanguage", b =>
                {
                    b.Property<Guid>("LectureProgrammingLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LectureProgrammingLanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LectureId");

                    b.ToTable("LectureProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("308a118a-6f6a-440c-afa2-88895049e6ca"),
                            LanguageId = new Guid("8665c6cb-7dc0-4058-9bc7-7c65c7869d47"),
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("61f7059c-734a-4496-8d80-b83f07b967b1"),
                            LanguageId = new Guid("48e36ba7-6216-4b19-a671-066c0f5a8e0a"),
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("f11956ae-db05-466e-bde0-471115927e09"),
                            LanguageId = new Guid("3a9723c8-af2c-46b9-a4cd-bcb32f5a90b6"),
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("9e7a5855-785b-4bc7-9251-28db028fd706"),
                            LanguageId = new Guid("bcd4aaec-f236-451a-92eb-7642471c8ecc"),
                            LectureId = new Guid("7e78b348-7834-44d3-ad9b-93155079e9be")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("fbd37832-32a2-4939-87d2-3189070538a8"),
                            LanguageId = new Guid("8665c6cb-7dc0-4058-9bc7-7c65c7869d47"),
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("1699efb5-0875-4b08-91de-0c62ad8767ef"),
                            LanguageId = new Guid("48e36ba7-6216-4b19-a671-066c0f5a8e0a"),
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("f0cc5ad3-f0a7-462c-9ebc-52638be5b74c"),
                            LanguageId = new Guid("3a9723c8-af2c-46b9-a4cd-bcb32f5a90b6"),
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f")
                        },
                        new
                        {
                            LectureProgrammingLanguageId = new Guid("d1fcf51a-06d8-43f2-9434-d0d36528bb5e"),
                            LanguageId = new Guid("bcd4aaec-f236-451a-92eb-7642471c8ecc"),
                            LectureId = new Guid("7c36d05c-333e-4970-8377-e5c96d25578f")
                        });
                });

            modelBuilder.Entity("Entitites.Models.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LanguageId");

                    b.Property<string>("LanguageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LanguageType")
                        .HasColumnType("int");

                    b.HasKey("LanguageId");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("8665c6cb-7dc0-4058-9bc7-7c65c7869d47"),
                            LanguageDescription = "Opis: C je opštepriznati proceduralni programski jezik koji je nastao u Bell Labs-u 1972. godine. Poznat je po svojoj efikasnosti, fleksibilnosti i mogućnosti direktnog pristupa hardveru.\r\nKarakteristike: Statički tipiziran, niskog nivoa apstrakcije, podržava pokazivače, omogućava direktno upravljanje memorijom.\r\nPrimeri upotrebe: Razvoj operativnih sistema, sistemske aplikacije, ugrađeni sistemi.",
                            LanguageName = "C",
                            LanguageType = 1
                        },
                        new
                        {
                            LanguageId = new Guid("48e36ba7-6216-4b19-a671-066c0f5a8e0a"),
                            LanguageDescription = "Opis: C++ je proširenje jezika C koje uvodi koncepte objektno-orijentisanog programiranja (OOP). Razvijen je kao unapređenje jezika C, omogućavajući programerima da koriste OOP paradigmu.\r\nKarakteristike: Objektno-orijentisan, podržava nasleđivanje, polimorfizam, apstrakciju i inkapsulaciju, bogata standardna biblioteka.\r\nPrimeri upotrebe: Razvoj softvera, igara, operativnih sistema, aplikacija za računarsko modelovanje.",
                            LanguageName = "C++",
                            LanguageType = 0
                        },
                        new
                        {
                            LanguageId = new Guid("3a9723c8-af2c-46b9-a4cd-bcb32f5a90b6"),
                            LanguageDescription = "Opis: C# je moderan, objektno-orijentisan jezik razvijen od strane Microsoft-a. Namenjen je razvoju aplikacija na platformi .NET.\r\nKarakteristike: Objektno-orijentisan, podržava garbage collection, delegati, događaji, LINQ (Language Integrated Query), Lambda izraze.\r\nPrimeri upotrebe: Razvoj Windows aplikacija, web aplikacija, igara, mobilnih aplikacija.",
                            LanguageName = "C#",
                            LanguageType = 0
                        },
                        new
                        {
                            LanguageId = new Guid("bcd4aaec-f236-451a-92eb-7642471c8ecc"),
                            LanguageDescription = "Opis: Java je objektno-orijentisan, platformski nezavisan jezik razvijen od strane Sun Microsystems-a (sada deo Oracle-a). Poznat je po svojoj sigurnosti i portabilnosti.\r\nKarakteristike: Objektno-orijentisan, platformski nezavisan (rad na različitim operativnim sistemima), podržava garbage collection, izuzetno popularan u razvoju web i mobilnih aplikacija.\r\nPrimeri upotrebe: Razvoj web aplikacija, mobilnih aplikacija (Android), serverskih aplikacija, finansijskih sistema.",
                            LanguageName = "Java",
                            LanguageType = 0
                        });
                });

            modelBuilder.Entity("Entitites.Models.Test", b =>
                {
                    b.Property<Guid>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LectureProgrammingLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestId");

                    b.HasIndex("LectureProgrammingLanguageId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Entitites.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f0091af6-14ee-4c5e-b913-30f987bac393",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b31df396-439a-4bb0-839b-1459b47a897f",
                            Email = "admin@test.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@TEST.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEPn31T7ZRlMTRN6mE2K9N7QuD9qfnrt/zdDTh6k7hvm37xFSyDhDfpHpcj+K+lZc7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "499dca4d-8888-4d90-be11-50733e3cb42b",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "a3da7156-4cca-44c8-ac03-2d6995589237",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "90bc5ebe-27cf-4f20-a969-dd1823e3dcb0",
                            Email = "user@test.com",
                            EmailConfirmed = true,
                            FirstName = "Basic",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@TEST.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAEAACcQAAAAEHMgNlTJvpDGJVTe61wq3RR1O2f0TteTHqzJUD00XBFWlMoQ9XYD9P101pK6k0hCjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "127f26d4-21c1-4056-b545-9531ee7c982c",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "23763795-6463-49b2-bc48-1348ce231ab0",
                            ConcurrencyStamp = "cbcc2410-a358-45c1-bf20-c07763f4e737",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "0b549254-d114-4132-b4f2-2e606080e507",
                            ConcurrencyStamp = "b4455b11-5ca6-4b06-94e2-421a759dbb04",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f0091af6-14ee-4c5e-b913-30f987bac393",
                            RoleId = "0b549254-d114-4132-b4f2-2e606080e507"
                        },
                        new
                        {
                            UserId = "a3da7156-4cca-44c8-ac03-2d6995589237",
                            RoleId = "23763795-6463-49b2-bc48-1348ce231ab0"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entitites.Models.Answer", b =>
                {
                    b.HasOne("Entitites.Models.Exercise", "Exercise")
                        .WithMany("Answers")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Entitites.Models.Exercise", b =>
                {
                    b.HasOne("Entitites.Models.Test", "Test")
                        .WithMany("Exercises")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Entitites.Models.LectureProgrammingLanguage", b =>
                {
                    b.HasOne("Entitites.Models.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany("Lectures")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entitites.Models.Lecture", "Lecture")
                        .WithMany("ProgrammingLanguages")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("Entitites.Models.Test", b =>
                {
                    b.HasOne("Entitites.Models.LectureProgrammingLanguage", "LectureProgrammingLanguage")
                        .WithMany("Tests")
                        .HasForeignKey("LectureProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LectureProgrammingLanguage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entitites.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entitites.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entitites.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entitites.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entitites.Models.Exercise", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Entitites.Models.Lecture", b =>
                {
                    b.Navigation("ProgrammingLanguages");
                });

            modelBuilder.Entity("Entitites.Models.LectureProgrammingLanguage", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Entitites.Models.ProgrammingLanguage", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("Entitites.Models.Test", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
